language: java
install:
  - git clone https://github.com/masterlemmi/commons.git
  - ./commons/gradlew build publishToMavenLocal

jdk:
  - oraclejdk8

services:
  - docker

script:
  - ./gradlew build
  - ./docker-travis.sh